language: cpp

matrix:
  include:
    - env: GCC_VERSION=6 BUILD_TYPE=Debug CPP=14 ASAN=Off LIBCXX=Off
      os: linux
      addons: &gcc6
        apt:
          packages:
            - g++-6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
      
before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script:
  - make
  - make test
  
notifications:
  email: false  